/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculator_CONSTANTS_H
#define calculator_CONSTANTS_H

#include "calculator_types.h"

namespace foo { namespace bar { namespace baz {

class calculatorConstants {
 public:
  calculatorConstants();

};

extern const calculatorConstants g_calculator_constants;

}}} // namespace

#endif
