/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculator_constants.h"

namespace foo { namespace bar { namespace baz {

const calculatorConstants g_calculator_constants;

calculatorConstants::calculatorConstants() {
}

}}} // namespace

